import{i as d,S as p,a as $}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();function y(e,o){e.forEach((s,a)=>{const t=P(s);o.insertAdjacentHTML("beforeend",t),a===e.length-1&&o.lastElementChild.scrollIntoView({behavior:"smooth",block:"end",inline:"nearest"})})}function P(e){return`
    <div class="card" data-large-image="${e.largeImageURL}">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" class="card-img" alt="${e.tags}">
      </a>
      <ul class="img-info">
        <li class="img-info-item">Likes: ${e.likes}</li>
        <li class="img-info-item">Views: ${e.views}</li>
        <li class="img-info-item">Comments: ${e.comments}</li>
        <li class="img-info-item">Downloads: ${e.downloads}</li>
      </ul>
    </div>
  `}const i=document.querySelector(".loader"),m=document.querySelector(".form"),v=document.querySelector(".search-input"),g=document.querySelector(".gallery"),h=document.querySelector(".load-more-btn");let n=1,f=0,l=0,b="",c=!0;m.addEventListener("submit",async e=>{e.preventDefault();const o=v.value.trim();if(i.style.display="inline-block",!o||o.length<3){d.error({message:"Search query must be at least 3 characters long",position:"topRight"}),i.style.display="none";return}try{const s=await w(o);b=o,f=s.totalHits,y(s.images,g,c),new p(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),L(f>n*15),c=!1}catch{}finally{i.style.display="none",m.reset()}});h.addEventListener("click",async()=>{i.style.display="inline-block",n++;try{const e=await w(b,n);y(e.images,g,c),new p(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),L(f>n*15),c=!1}catch{}finally{i.style.display="none"}});function L(e){h.style.display=e&&n<l?"block":"none"}async function w(e,o=1){const t=`https://pixabay.com/api/?key=42555164-0de9ae952fe9eb05e418ffbde&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{const r=await $.get(t);return r.data.hits.length===0?(d.info({message:"No images found",position:"topRight"}),g.innerHTML="",l=0):l=Math.ceil(r.data.totalHits/15),{images:r.data.hits,totalHits:r.data.totalHits,totalPages:l}}catch(r){return console.error("Error during search:",r.message),d.error({title:"Error",message:"An error occurred during the search",position:"topRight"}),{images:[],totalHits:0,totalPages:0}}}
//# sourceMappingURL=commonHelpers.js.map
