import{i as g,a as P,S as $}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&i(f)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();function h(e,o){e.forEach((s,i)=>{const t=v(s);o.insertAdjacentHTML("beforeend",t),i===e.length-1&&o.lastElementChild.scrollIntoView({behavior:"smooth",block:"end",inline:"nearest"})})}function v(e){return`
    <div class="card" data-large-image="${e.largeImageURL}">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" class="card-img" alt="${e.tags}">
      </a>
      <ul class="img-info">
        <li class="img-info-item">Likes: ${e.likes}</li>
        <li class="img-info-item">Views: ${e.views}</li>
        <li class="img-info-item">Comments: ${e.comments}</li>
        <li class="img-info-item">Downloads: ${e.downloads}</li>
      </ul>
    </div>
  `}const n=document.querySelector(".loader"),y=document.querySelector(".form"),E=document.querySelector(".search-input"),d=document.querySelector(".gallery"),c=document.querySelector(".load-more-btn");let a=1,m=0,l=0,b="",u=!0;function L(){new $(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}y.addEventListener("submit",async e=>{e.preventDefault(),d.innerHTML="";const o=E.value.trim();if(n.style.display="inline-block",!o||o.length<3){g.error({message:"Search query must be at least 3 characters long",position:"topRight"}),n.style.display="none";return}try{const s=await w(o);b=o,m=s.totalHits,h(s.images,d,u),L(),p(m>a*15),u=!1}catch(s){console.error(s)}finally{n.style.display="none",y.reset()}c.disabled=!1,c.style.cursor="pointer"});c.addEventListener("click",async()=>{n.style.display="inline-block",a++;try{const e=await w(b,a);h(e.images,d,u);const o=a<l;p(o),L(),p(m>a*15),u=!1}catch(e){console.error(e)}finally{n.style.display="none"}});function p(e){c.style.display=e&&a<l?"block":"none"}async function w(e,o=1){const t=`https://pixabay.com/api/?key=42555164-0de9ae952fe9eb05e418ffbde&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{const r=await P.get(t);return r.data.hits.length===0?(g.info({message:"No images found",position:"topRight"}),d.innerHTML="",l=0):l=Math.ceil(r.data.totalHits/15),{images:r.data.hits,totalHits:r.data.totalHits,totalPages:l}}catch(r){return console.error("Error during search:",r.message),g.error({title:"Error",message:"An error occurred during the search",position:"topRight"}),{images:[],totalHits:0,totalPages:0}}}window.addEventListener("load",()=>{c.style.display="none"});
//# sourceMappingURL=commonHelpers.js.map
