import{i as d,S as f}from"./assets/vendor-d9f1e717.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const L="42555164-0de9ae952fe9eb05e418ffbde";async function y(t,o=1,n=15){const s=`https://pixabay.com/api/?key=${L}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${n}`;try{const e=await fetch(s);if(!e.ok)throw new Error("Network response was not ok");const r=await e.json();if(r.hits.length===0)throw new Error("No images found");return{totalHits:r.totalHits,images:r.hits}}catch(e){throw e}}function g(t,o){const n=document.querySelector(o);n.innerHTML="",t.forEach(s=>{const e=$(s);n.insertAdjacentHTML("beforeend",e)})}function $(t){return`
    <div class="card" data-large-image="${t.largeImageURL}">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" class="card-img" alt="${t.tags}">
      </a>
      <ul class="img-info">
        <li class="img-info-item">Likes: ${t.likes}</li>
        <li class="img-info-item">Views: ${t.views}</li>
        <li class="img-info-item">Comments: ${t.comments}</li>
        <li class="img-info-item">Downloads: ${t.downloads}</li>
      </ul>
    </div>
  `}const i=document.querySelector(".loader"),u=document.querySelector(".form"),H=document.querySelector(".search-input"),l=".gallery",m=document.querySelector(".load-more-btn");let a=1,p=0,h="";u.addEventListener("submit",async t=>{t.preventDefault();const o=H.value.trim();if(i.style.display="inline-block",o.length<3){d.error({message:"Search query must be at least 3 characters long",position:"topRight"}),i.style.display="none";return}if(o===""){d.show({message:"Please write what you want to search",position:"topRight",color:"red"}),i.style.display="none";return}try{const n=await y(o),s=n.totalHits;h=o,p=s,g(n.images,l),l.innerHTML="",new f(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),w(s>a*15);const r=b();window.scrollBy(0,r*2)}catch(n){console.error(n)}finally{i.style.display="none",u.reset()}});m.addEventListener("click",async()=>{i.style.display="inline-block";try{a++;const t=await y(h,a);g(t.images,l),new f(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),w(p>a*15);const n=b();window.scrollBy(0,n*2)}catch(t){console.error(t)}finally{i.style.display="none"}});function w(t){m.style.display=t?"block":"none"}function b(){return document.querySelector(`${l} a`).getBoundingClientRect().height}
//# sourceMappingURL=commonHelpers.js.map
